catalog_app/urls.py
from django.urls import path
from .views import ListAllProfile
from .views import CreateProfile
from django.contrib.auth.views import (
    LoginView, LogoutView,
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView,
)
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .modules import views_category
from .modules import views_product
from .modules import views_catalog
# from django.views.generic import RedirectView
app_name = 'catalog'


urlpatterns = [
    # Rest Framework
    path("all-catalog", ListAllProfile.as_view(), name="all-catalog"),
    path("create-catalog", CreateProfile.as_view(), name="create-catalog"),

    path('', views_catalog.CatalogView.as_view(

    ), name="catalog"),
    path('category/', views_category.list_category, name="view-category"),

    path('category/create/', views_category.UploadImage.as_view(), name='upload_template'),
    path('category/view/<int:pk>/', views_category.UploadImageDisplay.as_view(), name='view_upload_template_page'),

    path('product/', views_product.list_product, name="view-product"),
    # path('', RedirectView.as_view(url='catalog-detail/', permanent=True)),
    path('product/create/', views_product.UploadImage.as_view(), name='upload_p_template'),
    path('product/view/<int:pk>/', views_product.UploadImageDisplay.as_view(), name='view_upload_p_template_page'),

]


django_template_practice1/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy #, include
from django.conf.urls import include

# from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (LoginView, LogoutView,
    PasswordChangeView, PasswordChangeDoneView,PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView,
)
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from django.views.generic.base import TemplateView
# # from book.views import homepage #1
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from datetime import datetime, date
from user_app.modules import views_auth
from user_app.modules import form_auth

urlpatterns = [
    path('', views_auth.index, name='index_admin'),
    # djoser endpoints: Django REST framework
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # =============| Admin site |============
    path('admin/', admin.site.urls),
    # path('auth/', include('authentication.urls')),
    # =============| app endpoints |============
    path("user/", include("user_app.urls")),
    path("catalog/", include("catalog_app.urls")),
    path('upload/', include('upload_app.urls')),
    # path('employee/', include('employee_app.urls')),

    # =============| Transmit Admin |============
    # .........................................
    # =============| password-reset for user |============
    path('user/accounts/password-reset/', PasswordResetView.as_view(
                title = 'Lấy lại mật khẩu',
                form_class = form_auth.ResetPassToEmailForm,
                template_name = 'registration/password_reset_form_new.html',
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Lấy lại mật khẩu', reverse_lazy('password_reset'))],'year':datetime.now().year},
                success_url='done/',
        ), name="password_reset"),
    path('user/accounts/password-reset/done/', PasswordResetDoneView.as_view(
                title = 'Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu',
                template_name = "registration/password_reset_done_new.html",
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu', reverse_lazy('password_reset_done'))],'year':datetime.now().year},
        ), name="password_reset_done"),
    #path('user/accounts/reset/<uidb64>/<token>/', ctrl_auth.PassResetView.as_view(), name="password_reset_confirm"),
    #Link được send vào mail
    path('user/accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                title = 'Đặt lại mật khẩu mới',
                form_class = form_auth.ResetPassForm,
                template_name = 'registration/password_reset_confirm_new.html',
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Đặt lại mật khẩu mới', reverse_lazy('password_reset_confirm'))],'year':datetime.now().year},
                success_url='/user/accounts/reset/done/',
        ), name="password_reset_confirm"),
    path('user/accounts/reset/done/', PasswordResetCompleteView.as_view(
                title = 'Đổi mật khẩu thành công',
                template_name = "registration/password_reset_complete_new.html",
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Đổi mật khẩu thành công', reverse_lazy('password_reset_complete'))],'year':datetime.now().year},
        ), name="password_reset_complete"),
]

# from django.conf import settings
# from django.conf.urls.static import static
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from .views import ListAllProfile
from .views import CreateProfile
from django.contrib.auth.views import (
    LoginView, LogoutView,
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView,
)
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from datetime import datetime, date

from django.urls import reverse_lazy
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .modules import form_auth
from .modules import views_auth
app_name = 'user'

urlpatterns = [
    # APIs: Django REST framework
    path("all-accounts", ListAllProfile.as_view(), name="all-accounts"),
    path("create-account", CreateProfile.as_view(), name="create-account"),

    # =============| Admin site |============
    # path('', admin.site.urls),
    path('', views_auth.index, name='index'),
    path('home/', views_auth.Homepage.as_view(), name='home'),
    path('accounts/', views_auth.AuthView.as_view(), name="accounts"),
    # Login form
    # path('accounts/login/', views_auth.loginUser.as_view(), name="login"),
    path('accounts/login/', views_auth.LoginView.as_view(), name="login"),
    path('accounts/login-social/', views_auth.LoginSocialView.as_view(), name="login_social"),

    path('accounts/logout/', auth_views.LogoutView.as_view(
            #template_name="registration/logged_out.html",
            next_page=reverse_lazy('user:login'), #next_page='/',
        ), name='logout'),
    path('accounts/sign-up/', views_auth.RegistrationUser.as_view(), name='sign_up'), #path('sign_up/', MySignUpView.as_view(), name='sign_up'),

    # =============| Profile |============
    path('profile/', views_auth.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views_auth.EditUserProfileView.as_view(), name='profile_edit'),
    path('profile/<int:gu_id>/edit/', views_auth.edit_profile_pk, name='profile_edit_pk'),

    # =============| Inside: password-reset for user |============
    path('accounts/password-change/', PasswordChangeView.as_view(
                title = 'Thay đổi mật khẩu',
                form_class = form_auth.PassChangeForm, template_name = 'registration/password_change_form_accounts.html',
                extra_context = {'next': reverse_lazy('user:password_change_done'), 'crumbs': [('Trang chủ', reverse_lazy('user:home')), ('Thông tin cá nhân', reverse_lazy('user:profile')), ('Thay đổi mật khẩu', reverse_lazy('user:password_change'))],'year':datetime.now().year},
                success_url='done/',
        ), name="password_change"),
    path('accounts/password-change/done/', PasswordChangeDoneView.as_view(
                title = 'Thay đổi mật khẩu thành công',
                extra_context = {'next': reverse_lazy('user:profile'), 'crumbs': [('Trang chủ', reverse_lazy('home')), ('Thông tin cá nhân', reverse_lazy('user:profile')), ('Thay đổi mật khẩu', reverse_lazy('user:password_change')), ('Thay đổi mật khẩu thành công', reverse_lazy('user:password_change_done'))],'year':datetime.now().year},
        ), name="password_change_done"),

    # =============| Outside: password-reset for user |============
    # path('accounts/password-reset/', PasswordResetView.as_view(
    #             title = 'Lấy lại mật khẩu',
    #             form_class = form_auth.ResetPassToEmailForm,
    #             template_name = 'registration/password_reset_form_new.html',
    #             # extra_context={'next': '/accounts/login/',
    #             #        'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')),
    #             #                   ('Lấy lại mật khẩu', reverse_lazy('user:password_reset'))],
    #             #        'year': datetime.now().year},
    #             success_url = reverse_lazy("user:password_reset_done")
    #             # success_url='done/',
    #     ), name="password_reset"),
    # path('accounts/password-reset/done/', PasswordResetDoneView.as_view(
    #             title = 'Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu',
    #             template_name = 'registration/password_reset_done_new.html',
    #             # extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')), ('Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu', reverse_lazy('user:password_reset_done'))],'year':datetime.now().year},
    #     ), name="password_reset_done"),
    # # path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    # #Link được send vào mail
    # path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
    #             title = 'Đặt lại mật khẩu mới',
    #             form_class = form_auth.ResetPassForm, template_name = 'registration/password_reset_form_new.html',
    #             extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')), ('Đặt lại mật khẩu mới', reverse_lazy('user:password_reset_confirm'))],'year':datetime.now().year},
    #             success_url = reverse_lazy("user:password_reset_complete")
    #             # success_url='/accounts/reset/done/',
    #     ), name="password_reset_confirm"),
    # path('accounts/reset/done/', PasswordResetCompleteView.as_view(
    #             title = 'Đổi mật khẩu thành công',
    #             extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')), ('Đổi mật khẩu thành công', reverse_lazy('user:password_reset_complete'))],'year':datetime.now().year},
    #     ), name="password_reset_complete"),

]


catalog_app/models.py
from django.db import models

# Create your models here.

catalog_app/models/category_model.py
from django.db import models
from django.contrib.auth.models import User
# from .product_model import Product
from datetime import datetime


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='catalogs/', null=True, default=None)
    content = models.TextField(max_length=1000, null=True, default=None)
    created_at = models.DateTimeField(null=True, default=datetime.now, blank=True)
    updated_at = models.DateTimeField(null=True, default=datetime.now, blank=True) # auto_now_add=True
    user = models.ForeignKey(User, on_delete=models.CASCADE) # One- Many
    # product = models.ManyToManyField(Product, help_text='Select a Product for this Catalog')
    PRODUCT_CHOICES = ()
    product_map = models.PositiveSmallIntegerField(choices=PRODUCT_CHOICES, null=True, default=0, blank=True)

    # Ko có cái này thì table tạo ra theo appname_classmodel
    # class Meta:
    #     managed = True
    #     db_table = 'catalogapp_catalog'
    class Meta:
        ordering = ['created_at', 'title']
        managed = True
        db_table = 'catalog_category'
        verbose_name = 'catalog_category'
        verbose_name_plural = 'catalog_categories'

    def __str__(self):
        return self.title
        # return f"{self.title}, {self.image}, {self.body}, {self.user}"

catalog_app/models/middleship_model.py
from .category_model import Category
from .product_model import Product


class Middleship(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date_joined = models.DateField()

catalog_app/models/product_model.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from datetime import datetime
# from user_app.models.account_model import Profile
from .category_model import Category
from django import forms


# @python_2_unicode_compatible
class Product(models.Model):
    p_title = models.CharField(max_length=255, null=True, default=None)
    p_name = models.CharField(max_length=100, null=True, default=None)
    p_code = models.CharField(max_length=50)
    p_image = models.ImageField(upload_to='products/', null=True, default=None)
    p_description = models.TextField(max_length=1000, null=True, default=None)
    p_country = models.CharField(max_length=50, null=True, default=None)
    created_at = models.DateTimeField(null=True, default=datetime.now, blank=True)
    updated_at = models.DateTimeField(null=True, default=datetime.now, blank=True)  # auto_now_add=True
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # category = models.ManyToManyField(Category, help_text='Select a Category for this Product')
    middles = models.ManyToManyField(Category, through='Middleship')

    def __str__(self):
        return self.p_title
        # return f"{self.p_title}, {self.p_name}, {self.p_code}, {self.p_date}, {self.p_country}"

    # def __unicode__(self):
    #     return u"%s" % self.user

    class Meta:
        ordering = ['created_at', 'p_name']
        managed = True
        db_table = 'catalog_product'
        verbose_name = 'catalog_product'
        verbose_name_plural = 'catalog_products'


class Middleship(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date_joined = models.DateField(null=True, default=datetime.now)

    def __str__(self):
        return "{}_{}".format(self.Product.__str__(), self.Category.__str__())

catalog_app/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework.generics import ListAPIView, GenericAPIView
from rest_framework.permissions import IsAuthenticated
# from .models import Book
from user_app.models.account_model import Profile
from .serializers import User_appSerializer
from rest_framework.mixins import CreateModelMixin


# Get all
class ListAllProfile(ListAPIView):
    queryset = Profile.objects.all()
    serializer_class = User_appSerializer
    permission_classes = [IsAuthenticated]


class CreateProfile(CreateModelMixin, GenericAPIView):
    serializer_class = User_appSerializer
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        # print(self.request.data)
        # print(self.request.data.get("name"))
        return self.create(request, *args, **kwargs)

    # def perform_create(self, serializer):
    #    _id = self.request.data.get('id')
    #    comment = get_object_or_404(Profile, pk=_id)
    #    print(comment)

catalog_app/templates/blog/upload_category.html
{% extends "layout/layout.html" %}

{% block title %}{{ title }} {% endblock %}

{% block nav_top %}{% include 'layout/nav-bar_top.html' %}{% endblock %}

{% block nav_sidebar %}{% include 'layout/nav-sidebar.html' %}{% endblock %}

{% block content %}
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
    {% include 'layout/nav-bar.html' %}

{% endblock %}

catalog_app/templates/blog/upload_category_display.html
{% extends "layout/layout.html" %}

{% load static %}
{% block title %}{{ title }} {% endblock %}

{% block nav_top %}{% include 'layout/nav-bar_top.html' %}{% endblock %}

{% block nav_sidebar %}{% include 'layout/nav-sidebar.html' %}{% endblock %}

{% block content %}
    <a href="{% url 'catalog:view-category' %}">Go Back</a>
    <hr/>
    <h1>{{UF.title}}</h1>
    <img src="{{UF.image.url}}" alt="Smiley face" width="250" height="250">

    {% include 'layout/nav-bar.html' %}

{% endblock %}

catalog_app/templates/blog/upload_product.html
{% extends "layout/layout.html" %}

{% block title %}{{ title }} {% endblock %}

{% block nav_top %}{% include 'layout/nav-bar_top.html' %}{% endblock %}

{% block nav_sidebar %}{% include 'layout/nav-sidebar.html' %}{% endblock %}

{% block content %}
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
    {% include 'layout/nav-bar.html' %}

{% endblock %}

catalog_app/templates/blog/upload_product_display.html
{% extends "layout/layout.html" %}

{% load static %}
{% block title %}{{ title }} {% endblock %}

{% block nav_top %}{% include 'layout/nav-bar_top.html' %}{% endblock %}

{% block nav_sidebar %}{% include 'layout/nav-sidebar.html' %}{% endblock %}

{% block content %}
    <a href="{% url 'catalog:upload_p_template' %}">Go Back</a>
    <hr/>
    <h1>Tiêu đề: {{UF.p_title}}</h1>
    <h6>Tên sản phẩm: {{UF.p_name}}</h6>
    <h5>Mã sản phẩm: {{UF.p_code}}</h5>
    <h6>Xuất xứ: {{UF.p_country}}</h6>
    <h6>Người tạo: {{UF.author}}</h6>
    <p><img src="{{UF.p_image.url}}" alt="Smiley face" width="250" height="250"></p>
    <h6>Mô tả: {{UF.p_description}}</h6>

    {% include 'layout/nav-bar.html' %}
{% endblock %}

catalog_app/templates/blog/view_category.html
{% extends "layout/layout.html" %}

{% block title %}{{ title }} {% endblock %}

{% block nav_top %}{% include 'layout/nav-bar_top.html' %}{% endblock %}

{% block nav_sidebar %}{% include 'layout/nav-sidebar.html' %}{% endblock %}

{% block content %}
<!--<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Catalog</title>
    <style>
        .pagination a {
            border: 1px solid black;
            padding: 2px
        }
    </style>
</head>
<body>-->
    <div class="home-page">
		<ul id="tree">
			<li class="open"><a href="{% url 'catalog:upload_template' %}"><strong>Thêm vào CATALOG_CATEGORY</strong></a>
			</li>
		</ul>
	</div>
    <hr/>
    <a href="{% url 'catalog:catalog' %}">Go Back</a>
    {% for item in page_obj %}
        <h2>Tiêu đề: {{item.title}}</h2>
        <h6>Người tạo: {{item.user.last_name}} {{item.user.first_name}}</h6>
        <p><img src="{{item.image.url}}" alt="Smiley face" width="250" height="250"></p>
        <p>Nội dung: {{item.content}}</p>
        <hr/>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
<!--
</body>
</html>-->
    <!--Add this-->
    {% include 'layout/nav-bar.html' %}

{% endblock %}

catalog_app/templates/blog/view_product.html
{% extends "layout/layout.html" %}

{% block title %}{{ title }} {% endblock %}

{% block nav_top %}{% include 'layout/nav-bar_top.html' %}{% endblock %}

{% block nav_sidebar %}{% include 'layout/nav-sidebar.html' %}{% endblock %}

{% block content %}
<!--<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Catalog</title>
    <style>
        .pagination a {
            border: 1px solid black;
            padding: 2px
        }
    </style>
</head>
<body>-->
    <div class="home-page">
		<ul id="tree">
			<li class="open"><a href="{% url 'catalog:upload_p_template' %}"><strong>Thêm vào CATALOG_PRODUCT</strong></a>
			</li>
		</ul>
	</div>
    <hr/>
    <a href="{% url 'catalog:catalog' %}">Go Back</a>
    {% for item in page_obj %}
        <h1>Tiêu đề: {{item.p_title}}</h1>
        <h6>Tên sản phẩm: {{item.p_name}}</h6>
        <h5>Mã sản phẩm: {{item.p_code}}</h5>
        <h6>Xuất xứ: {{item.p_country}}</h6>
        <h6>Người tạo: {{item.user.last_name}} {{item.user.first_name}}</h6>
        <p><img src="{{item.p_image.url}}" alt="Smiley face" width="700" height="350"></p>
        <h6>Mô tả: {{item.p_description}}</h6>
        <hr/>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
<!--
</body>
</html>-->
    <!--Add this-->
    {% include 'layout/nav-bar.html' %}

{% endblock %}