django_template_practice1/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy #, include
from django.conf.urls import include

# from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (LoginView, LogoutView,
    PasswordChangeView, PasswordChangeDoneView,PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView,
)
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from django.views.generic.base import TemplateView
# # from book.views import homepage #1
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from datetime import datetime, date
from user_app.modules import views_auth
from user_app.modules import form_auth

urlpatterns = [
    path('', views_auth.index, name='index_admin'),
    # djoser endpoints: Django REST framework
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # =============| Admin site |============
    path('admin/', admin.site.urls),
    # path('auth/', include('authentication.urls')),
    # =============| app endpoints |============
    path("user/", include("user_app.urls")),
    path("catalog/", include("catalog_app.urls")),
    path('upload/', include('upload_app.urls')),
    # path('employee/', include('employee_app.urls')),

    # =============| Transmit Admin |============
    # .........................................
    # =============| password-reset for user |============
    path('user/accounts/password-reset/', PasswordResetView.as_view(
                title = 'Lấy lại mật khẩu',
                form_class = form_auth.ResetPassToEmailForm,
                template_name = 'registration/password_reset_form_new.html',
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Lấy lại mật khẩu', reverse_lazy('password_reset'))],'year':datetime.now().year},
                success_url='done/',
        ), name="password_reset"),
    path('user/accounts/password-reset/done/', PasswordResetDoneView.as_view(
                title = 'Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu',
                template_name = "registration/password_reset_done_new.html",
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu', reverse_lazy('password_reset_done'))],'year':datetime.now().year},
        ), name="password_reset_done"),
    #path('user/accounts/reset/<uidb64>/<token>/', ctrl_auth.PassResetView.as_view(), name="password_reset_confirm"),
    #Link được send vào mail
    path('user/accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                title = 'Đặt lại mật khẩu mới',
                form_class = form_auth.ResetPassForm,
                template_name = 'registration/password_reset_confirm_new.html',
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Đặt lại mật khẩu mới', reverse_lazy('password_reset_confirm'))],'year':datetime.now().year},
                success_url='/user/accounts/reset/done/',
        ), name="password_reset_confirm"),
    path('user/accounts/reset/done/', PasswordResetCompleteView.as_view(
                title = 'Đổi mật khẩu thành công',
                template_name = "registration/password_reset_complete_new.html",
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Đổi mật khẩu thành công', reverse_lazy('password_reset_complete'))],'year':datetime.now().year},
        ), name="password_reset_complete"),
]

# from django.conf import settings
# from django.conf.urls.static import static
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from .views import ListAllProfile
from .views import CreateProfile
from django.contrib.auth.views import (
    LoginView, LogoutView,
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView,
)
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from datetime import datetime, date

from django.urls import reverse_lazy
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .modules import form_auth
from .modules import views_auth
app_name = 'user'

urlpatterns = [
    # APIs: Django REST framework
    path("all-accounts", ListAllProfile.as_view(), name="all-accounts"),
    path("create-account", CreateProfile.as_view(), name="create-account"),

    # =============| Admin site |============
    # path('', admin.site.urls),
    path('', views_auth.index, name='index'),
    path('home/', views_auth.Homepage.as_view(), name='home'),
    path('accounts/', views_auth.AuthView.as_view(), name="accounts"),
    # Login form
    # path('accounts/login/', views_auth.loginUser.as_view(), name="login"),
    path('accounts/login/', views_auth.LoginView.as_view(), name="login"),
    path('accounts/login-social/', views_auth.LoginSocialView.as_view(), name="login_social"),

    path('accounts/logout/', auth_views.LogoutView.as_view(
            #template_name="registration/logged_out.html",
            next_page=reverse_lazy('user:login'), #next_page='/',
        ), name='logout'),
    path('accounts/sign-up/', views_auth.RegistrationUser.as_view(), name='sign_up'), #path('sign_up/', MySignUpView.as_view(), name='sign_up'),

    # =============| Profile |============
    path('profile/', views_auth.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views_auth.EditUserProfileView.as_view(), name='profile_edit'),
    path('profile/<int:gu_id>/edit/', views_auth.edit_profile_pk, name='profile_edit_pk'),

    # =============| Inside: password-reset for user |============
    path('accounts/password-change/', PasswordChangeView.as_view(
                title = 'Thay đổi mật khẩu',
                form_class = form_auth.PassChangeForm, template_name = 'registration/password_change_form_accounts.html',
                extra_context = {'next': reverse_lazy('user:password_change_done'), 'crumbs': [('Trang chủ', reverse_lazy('user:home')), ('Thông tin cá nhân', reverse_lazy('user:profile')), ('Thay đổi mật khẩu', reverse_lazy('user:password_change'))],'year':datetime.now().year},
                success_url='done/',
        ), name="password_change"),
    path('accounts/password-change/done/', PasswordChangeDoneView.as_view(
                title = 'Thay đổi mật khẩu thành công',
                extra_context = {'next': reverse_lazy('user:profile'), 'crumbs': [('Trang chủ', reverse_lazy('home')), ('Thông tin cá nhân', reverse_lazy('user:profile')), ('Thay đổi mật khẩu', reverse_lazy('user:password_change')), ('Thay đổi mật khẩu thành công', reverse_lazy('user:password_change_done'))],'year':datetime.now().year},
        ), name="password_change_done"),

    # =============| Outside: password-reset for user |============
    # path('accounts/password-reset/', PasswordResetView.as_view(
    #             title = 'Lấy lại mật khẩu',
    #             form_class = form_auth.ResetPassToEmailForm,
    #             template_name = 'registration/password_reset_form_new.html',
    #             # extra_context={'next': '/accounts/login/',
    #             #        'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')),
    #             #                   ('Lấy lại mật khẩu', reverse_lazy('user:password_reset'))],
    #             #        'year': datetime.now().year},
    #             success_url = reverse_lazy("user:password_reset_done")
    #             # success_url='done/',
    #     ), name="password_reset"),
    # path('accounts/password-reset/done/', PasswordResetDoneView.as_view(
    #             title = 'Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu',
    #             template_name = 'registration/password_reset_done_new.html',
    #             # extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')), ('Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu', reverse_lazy('user:password_reset_done'))],'year':datetime.now().year},
    #     ), name="password_reset_done"),
    # # path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    # #Link được send vào mail
    # path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
    #             title = 'Đặt lại mật khẩu mới',
    #             form_class = form_auth.ResetPassForm, template_name = 'registration/password_reset_form_new.html',
    #             extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')), ('Đặt lại mật khẩu mới', reverse_lazy('user:password_reset_confirm'))],'year':datetime.now().year},
    #             success_url = reverse_lazy("user:password_reset_complete")
    #             # success_url='/accounts/reset/done/',
    #     ), name="password_reset_confirm"),
    # path('accounts/reset/done/', PasswordResetCompleteView.as_view(
    #             title = 'Đổi mật khẩu thành công',
    #             extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')), ('Đổi mật khẩu thành công', reverse_lazy('user:password_reset_complete'))],'year':datetime.now().year},
    #     ), name="password_reset_complete"),

]


catalog_app/models/product_model.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from datetime import datetime
# from user_app.models.account_model import Profile
from .category_model import Category
from django import forms


# @python_2_unicode_compatible
class Product(models.Model):
    p_title = models.CharField(max_length=255, null=True, default=None)
    p_name = models.CharField(max_length=100, null=True, default=None)
    p_code = models.CharField(max_length=50)
    p_image = models.ImageField(upload_to='products/', null=True, default=None)
    p_description = models.TextField(max_length=1000, null=True, default=None)
    p_country = models.CharField(max_length=50, null=True, default=None)
    created_at = models.DateTimeField(null=True, default=datetime.now, blank=True)
    updated_at = models.DateTimeField(null=True, default=datetime.now, blank=True)  # auto_now_add=True
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # category = models.ManyToManyField(Category, help_text='Select a Category for this Product')
    middles = models.ManyToManyField(Category, through='Middleship')

    def __str__(self):
        return self.p_title
        # return f"{self.p_title}, {self.p_name}, {self.p_code}, {self.p_date}, {self.p_country}"

    # def __unicode__(self):
    #     return u"%s" % self.user

    class Meta:
        ordering = ['created_at', 'p_name']
        managed = True
        db_table = 'catalog_product'
        verbose_name = 'catalog_product'
        verbose_name_plural = 'catalog_products'


class Middleship(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date_joined = models.DateField(null=True, default=datetime.now)

    def __str__(self):
        return "{}_{}".format(self.Product.__str__(), self.Category.__str__())

user_app/models/account_model.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from datetime import datetime


# @python_2_unicode_compatible
class Profile(models.Model):
    # id = models.AutoField(primary_key=True, serialize=False)  # phiên bản python 3.9 bắt buộc phải đ/n khóa chính
    # id = models.AutoField(auto_create=True, serialize=False)
    LOCAL_ACCOUNT = 0
    GOOGLE = 1
    FACEBOOK = 2
    LINKEDIN = 3
    SOCIAL_CHOICES = (
        (LOCAL_ACCOUNT, 'Local account'),
        (GOOGLE, 'Google'),
        (FACEBOOK, 'Facebook'),
        (LINKEDIN, 'Linkedin'),
    )
    social_network = models.PositiveSmallIntegerField(choices=SOCIAL_CHOICES, null=True, default=0, blank=True)
    birthday = models.DateField(null=True, default=None, blank=True)
    phone_number = models.CharField(max_length=20, null=True, default=None)
    address = models.CharField(max_length=150, null=True, default=None)
    description = models.CharField(max_length=100, null=True, default=None)
    website = models.URLField(max_length=256, null=True, default=None)
    images = models.ImageField(upload_to='images', null=True, default=None)
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # id table user
    created_at = models.DateTimeField(null=True, default=datetime.now, blank=True)
    updated_at = models.DateTimeField(null=True, default=datetime.now, blank=True)  # auto_now_add=True

    class Meta:
        ordering = ['created_at', 'birthday']
        # managed = True
        db_table = 'profile'
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

    def __str__(self):
        return self.user.username


# @receiver(post_save, sender=User)
# def create_or_update_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#     instance.profile.save()


user_app/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework.generics import ListAPIView, GenericAPIView
from rest_framework.permissions import IsAuthenticated
# from .models import Book
from .models.account_model import Profile
from .serializers import User_appSerializer
from rest_framework.mixins import CreateModelMixin


# Get all
class ListAllProfile(ListAPIView):
    queryset = Profile.objects.all()
    serializer_class = User_appSerializer
    permission_classes = [IsAuthenticated]


class CreateProfile(CreateModelMixin, GenericAPIView):
    serializer_class = User_appSerializer
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        # print(self.request.data)
        # print(self.request.data.get("name"))
        return self.create(request, *args, **kwargs)

    # def perform_create(self, serializer):
    #    _id = self.request.data.get('id')
    #    comment = get_object_or_404(Author, pk=_id)
    #    print(comment)

user_app/templates/profile/profile_edit.html
{% extends "layout/layout.html" %} 

{% block title %}{{ title }} {% endblock %} 

{% block nav_top %}{% include 'layout/nav-bar_top.html' %}{% endblock %}

{% block nav_sidebar %}{% include 'layout/nav-sidebar.html' %}{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
	<nav aria-label="breadcrumb">
  		<ol class="breadcrumb">
		{% for crumb, href in crumbs %}
	      {% if forloop.last %}
	        <li class="breadcrumb-item{% if forloop.counter == breadcrumbs_total %} active{% endif %}" {% if forloop.counter == breadcrumbs_total %}aria-current="page"{% endif %}>{{ crumb }}</li>
	      {% else %}
	        <li class="breadcrumb-item"><a href="{{ href }}">{{ crumb }}</a></li>
	      {% endif %}
	    {% endfor %}
		</ol>
	</nav>
</div>
{% endblock %}

{% block content %}
<div class="">
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %} 
		{% for field in user_form %}
	    <div class="form-group clearfix">
	    	<label for="id_username" class="col-md-4 control-label">{{ field.label }}</label>
	    	<div class="col-md-4" style="display: inline-block;">{{ field }}</div>
	    </div>
	    {% endfor %}
	    <div class="clearfix"></div><!-- {{ profile_form.as_p }} -->
	    {% for field in profile_form %}
	    <div class="form-group clearfix">
	    	<label for="id_username" class="col-md-4 control-label">{{ field.label }}</label>
	    	<div class="col-md-4" style="display: inline-block;">{{ field }}</div>
	    </div>
	    {% endfor %}
	    <div class="form-group clearfix">
			<input type="hidden" name="next" value="{{ next }}" />
			<div class="col-md-12" style="text-align: center;"><input type="submit" value="Lưu lại" class="btn-info"/></div>
		</div>
	</form>
</div>
{% endblock %}

user_app/templates/profile/profile_view.html
{% extends "layout/layout.html" %}

{% block title %}{{ title }} {% endblock %}

{% block content %}
	<div class="">
	 	{% load static %}
		<div class="form-group clearfix">
			<label for="id_username" class="col-md-4 control-label">Tên đăng nhập (*)</label>
			<label for="id_username" class="col-md-7 required-color">{{ user.username }}</label>
		</div>
		<div class="form-group clearfix">
			<label for="id_first_name" class="col-md-4 control-label">Tên (*)</label>
			<label for="id_first_name" class="col-md-7 required-color">{{ user.first_name }}</label>
		</div>
		<div class="form-group clearfix">
			<label for="id_last_name" class="col-md-4 control-label">Họ (*)</label>
			<label for="id_last_name" class="col-md-7 required-color">{{ user.last_name }}</label>
		</div>
		<div class="form-group clearfix">
			<label for="id_email" class="col-md-4 control-label">Mail điện tử</label>
			<label for="id_email" class="col-md-7 required-color">{{ user.email }}</label>
			<!-- <input type="text" value="{{ user.email }}" name="username" visibility="hidden" /> -->
		</div>
		<div class="form-group clearfix">
			<label for="id_is_staff" class="col-md-4 control-label">Tình trạng hân viên</label>
			<label for="id_is_staff" class="col-md-7 required-color">{{ user.is_staff }}</label>
		</div>
		<div class="form-group clearfix">
			<label for="id_is_active" class="col-md-4 control-label">Kích hoạt</label>
			<label for="id_is_active" class="col-md-7 required-color">{{ user.is_active }}</label>
		</div>
		<div class="form-group clearfix">
			<label for="id_date_joined" class="col-md-4 control-label">Ngày tham gia</label>
			<label for="id_date_joined" class="col-md-7 required-color">{{ user.date_joined }}</label>
		</div>
		<div class="form-group clearfix">
			<label for="id_role" class="col-md-4 control-label">Tài khoản (Local | Social)</label>
			<label for="id_role" class="col-md-7 required-color">{{ author.social_network }}</label>
		</div>
		<div class="form-group clearfix">
			<label for="id_birthday" class="col-md-4 control-label">Ngày sinh (*)</label>
			<label for="id_birthday" class="col-md-7 required-color">{{ author.birthday }}</label>
		</div>
		<div class="form-group clearfix">
			<label for="id_phoneNumber" class="col-md-4 control-label">Số điện thoại</label>
			<label for="id_phoneNumber" class="col-md-7 required-color">{{ author.phone_number }}</label>
		</div>
		<div class="form-group clearfix">
			<label for="id_address" class="col-md-4 control-label">Địa chỉ</label>
			<label for="id_address" class="col-md-7 required-color">{{ author.address }}</label>
		</div>
		<div class="form-group clearfix">
			<label for="id_description" class="col-md-4 control-label">Mô tả</label>
			<label for="id_description" class="col-md-7 required-color">{{ author.description }}</label>
		</div>
		<div class="form-group clearfix">
			<label for="id_website" class="col-md-4 control-label">Link cá nhân</label>
			<label for="id_website" class="col-md-7 required-color">{{ author.website }}</label>
		</div>

		<div class="form-group clearfix">
			{% if user.profile.images %}
			<label for="id_address" class="col-md-4 control-label"><img src="{{ author.images.url }}" alt="{{ user.profile.images }}" style="width: 200px;" /></label>
			<label for="id_images" class="col-md-4 required-color">{{ author.images.url }}</label>
			<!-- <img src="{{ MEDIA_URL }}{{ profile_record.images }}" alt="{{ profile_record.images }}" /> -->
			{% else %}
			<label for="id_address" class="col-md-4 control-label"><img src="{% static 'images/avatar.png' %}" alt="Default" style="width: 200px;" /></label>
			<label for="id_images" class="col-md-4 required-color">Hình Avatar mặc định</label>
			{% endif %}
		</div>
		<div class="form-group clearfix">
		<ul>
			<!-- <li><a href="{% url 'user:profile' %}{{ user.id }}/edit/">Chỉnh sửa thông tin cá nhân</a></li> -->
			<li style="text-align: center;list-style: none;"><a href="{% url 'user:profile' %}edit/">Chỉnh sửa thông tin cá nhân</a></li>
			<li style="text-align: center;list-style: none;"><a href="{% url 'user:password_change' %}">Thay đổi mật khẩu</a></li>
		</ul>
		</div>
	</div>
{% endblock %}