django_template_practice1/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy #, include
from django.conf.urls import include

# from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (LoginView, LogoutView,
    PasswordChangeView, PasswordChangeDoneView,PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView,
)
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from django.views.generic.base import TemplateView
# # from book.views import homepage #1
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from datetime import datetime, date
from user_app.modules import views_auth
from user_app.modules import form_auth

urlpatterns = [
    path('', views_auth.index, name='index_admin'),
    # djoser endpoints: Django REST framework
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # =============| Admin site |============
    path('admin/', admin.site.urls),
    # path('auth/', include('authentication.urls')),
    # =============| app endpoints |============
    path("user/", include("user_app.urls")),
    path("catalog/", include("catalog_app.urls")),
    path('upload/', include('upload_app.urls')),
    # path('employee/', include('employee_app.urls')),

    # =============| Transmit Admin |============
    # .........................................
    # =============| password-reset for user |============
    path('user/accounts/password-reset/', PasswordResetView.as_view(
                title = 'Lấy lại mật khẩu',
                form_class = form_auth.ResetPassToEmailForm,
                template_name = 'registration/password_reset_form_new.html',
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Lấy lại mật khẩu', reverse_lazy('password_reset'))],'year':datetime.now().year},
                success_url='done/',
        ), name="password_reset"),
    path('user/accounts/password-reset/done/', PasswordResetDoneView.as_view(
                title = 'Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu',
                template_name = "registration/password_reset_done_new.html",
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu', reverse_lazy('password_reset_done'))],'year':datetime.now().year},
        ), name="password_reset_done"),
    #path('user/accounts/reset/<uidb64>/<token>/', ctrl_auth.PassResetView.as_view(), name="password_reset_confirm"),
    #Link được send vào mail
    path('user/accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                title = 'Đặt lại mật khẩu mới',
                form_class = form_auth.ResetPassForm,
                template_name = 'registration/password_reset_confirm_new.html',
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Đặt lại mật khẩu mới', reverse_lazy('password_reset_confirm'))],'year':datetime.now().year},
                success_url='/user/accounts/reset/done/',
        ), name="password_reset_confirm"),
    path('user/accounts/reset/done/', PasswordResetCompleteView.as_view(
                title = 'Đổi mật khẩu thành công',
                template_name = "registration/password_reset_complete_new.html",
                extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('index')), ('Đăng nhập', reverse_lazy('login')), ('Đổi mật khẩu thành công', reverse_lazy('password_reset_complete'))],'year':datetime.now().year},
        ), name="password_reset_complete"),
]

# from django.conf import settings
# from django.conf.urls.static import static
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from .views import ListAllProfile
from .views import CreateProfile
from django.contrib.auth.views import (
    LoginView, LogoutView,
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView,
)
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from datetime import datetime, date

from django.urls import reverse_lazy
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .modules import form_auth
from .modules import views_auth
app_name = 'user'

urlpatterns = [
    # APIs: Django REST framework
    path("all-accounts", ListAllProfile.as_view(), name="all-accounts"),
    path("create-account", CreateProfile.as_view(), name="create-account"),

    # =============| Admin site |============
    # path('', admin.site.urls),
    path('', views_auth.index, name='index'),
    path('home/', views_auth.Homepage.as_view(), name='home'),
    path('accounts/', views_auth.AuthView.as_view(), name="accounts"),
    # Login form
    # path('accounts/login/', views_auth.loginUser.as_view(), name="login"),
    path('accounts/login/', views_auth.LoginView.as_view(), name="login"),
    path('accounts/login-social/', views_auth.LoginSocialView.as_view(), name="login_social"),

    path('accounts/logout/', auth_views.LogoutView.as_view(
            #template_name="registration/logged_out.html",
            next_page=reverse_lazy('user:login'), #next_page='/',
        ), name='logout'),
    path('accounts/sign-up/', views_auth.RegistrationUser.as_view(), name='sign_up'), #path('sign_up/', MySignUpView.as_view(), name='sign_up'),

    # =============| Profile |============
    path('profile/', views_auth.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views_auth.EditUserProfileView.as_view(), name='profile_edit'),
    path('profile/<int:gu_id>/edit/', views_auth.edit_profile_pk, name='profile_edit_pk'),

    # =============| Inside: password-reset for user |============
    path('accounts/password-change/', PasswordChangeView.as_view(
                title = 'Thay đổi mật khẩu',
                form_class = form_auth.PassChangeForm, template_name = 'registration/password_change_form_accounts.html',
                extra_context = {'next': reverse_lazy('user:password_change_done'), 'crumbs': [('Trang chủ', reverse_lazy('user:home')), ('Thông tin cá nhân', reverse_lazy('user:profile')), ('Thay đổi mật khẩu', reverse_lazy('user:password_change'))],'year':datetime.now().year},
                success_url='done/',
        ), name="password_change"),
    path('accounts/password-change/done/', PasswordChangeDoneView.as_view(
                title = 'Thay đổi mật khẩu thành công',
                extra_context = {'next': reverse_lazy('user:profile'), 'crumbs': [('Trang chủ', reverse_lazy('home')), ('Thông tin cá nhân', reverse_lazy('user:profile')), ('Thay đổi mật khẩu', reverse_lazy('user:password_change')), ('Thay đổi mật khẩu thành công', reverse_lazy('user:password_change_done'))],'year':datetime.now().year},
        ), name="password_change_done"),

    # =============| Outside: password-reset for user |============
    # path('accounts/password-reset/', PasswordResetView.as_view(
    #             title = 'Lấy lại mật khẩu',
    #             form_class = form_auth.ResetPassToEmailForm,
    #             template_name = 'registration/password_reset_form_new.html',
    #             # extra_context={'next': '/accounts/login/',
    #             #        'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')),
    #             #                   ('Lấy lại mật khẩu', reverse_lazy('user:password_reset'))],
    #             #        'year': datetime.now().year},
    #             success_url = reverse_lazy("user:password_reset_done")
    #             # success_url='done/',
    #     ), name="password_reset"),
    # path('accounts/password-reset/done/', PasswordResetDoneView.as_view(
    #             title = 'Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu',
    #             template_name = 'registration/password_reset_done_new.html',
    #             # extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')), ('Gửi yêu cầu thành công. Vào email để lấy lại mật khẩu', reverse_lazy('user:password_reset_done'))],'year':datetime.now().year},
    #     ), name="password_reset_done"),
    # # path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    # #Link được send vào mail
    # path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
    #             title = 'Đặt lại mật khẩu mới',
    #             form_class = form_auth.ResetPassForm, template_name = 'registration/password_reset_form_new.html',
    #             extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')), ('Đặt lại mật khẩu mới', reverse_lazy('user:password_reset_confirm'))],'year':datetime.now().year},
    #             success_url = reverse_lazy("user:password_reset_complete")
    #             # success_url='/accounts/reset/done/',
    #     ), name="password_reset_confirm"),
    # path('accounts/reset/done/', PasswordResetCompleteView.as_view(
    #             title = 'Đổi mật khẩu thành công',
    #             extra_context = {'next':'/accounts/login/', 'crumbs': [('Trang chủ', reverse_lazy('user:index')), ('Đăng nhập', reverse_lazy('user:login')), ('Đổi mật khẩu thành công', reverse_lazy('user:password_reset_complete'))],'year':datetime.now().year},
    #     ), name="password_reset_complete"),

]


user_app/models/account_model.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from datetime import datetime


# @python_2_unicode_compatible
class Profile(models.Model):
    # id = models.AutoField(primary_key=True, serialize=False)  # phiên bản python 3.9 bắt buộc phải đ/n khóa chính
    # id = models.AutoField(auto_create=True, serialize=False)
    LOCAL_ACCOUNT = 0
    GOOGLE = 1
    FACEBOOK = 2
    LINKEDIN = 3
    SOCIAL_CHOICES = (
        (LOCAL_ACCOUNT, 'Local account'),
        (GOOGLE, 'Google'),
        (FACEBOOK, 'Facebook'),
        (LINKEDIN, 'Linkedin'),
    )
    social_network = models.PositiveSmallIntegerField(choices=SOCIAL_CHOICES, null=True, default=0, blank=True)
    birthday = models.DateField(null=True, default=None, blank=True)
    phone_number = models.CharField(max_length=20, null=True, default=None)
    address = models.CharField(max_length=150, null=True, default=None)
    description = models.CharField(max_length=100, null=True, default=None)
    website = models.URLField(max_length=256, null=True, default=None)
    images = models.ImageField(upload_to='images', null=True, default=None)
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # id table user
    created_at = models.DateTimeField(null=True, default=datetime.now, blank=True)
    updated_at = models.DateTimeField(null=True, default=datetime.now, blank=True)  # auto_now_add=True

    class Meta:
        ordering = ['created_at', 'birthday']
        # managed = True
        db_table = 'profile'
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

    def __str__(self):
        return self.user.username


# @receiver(post_save, sender=User)
# def create_or_update_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#     instance.profile.save()


user_app/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework.generics import ListAPIView, GenericAPIView
from rest_framework.permissions import IsAuthenticated
# from .models import Book
from .models.account_model import Profile
from .serializers import User_appSerializer
from rest_framework.mixins import CreateModelMixin


# Get all
class ListAllProfile(ListAPIView):
    queryset = Profile.objects.all()
    serializer_class = User_appSerializer
    permission_classes = [IsAuthenticated]


class CreateProfile(CreateModelMixin, GenericAPIView):
    serializer_class = User_appSerializer
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        # print(self.request.data)
        # print(self.request.data.get("name"))
        return self.create(request, *args, **kwargs)

    # def perform_create(self, serializer):
    #    _id = self.request.data.get('id')
    #    comment = get_object_or_404(Author, pk=_id)
    #    print(comment)

user_app/templates/layout/layout.html

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- <meta charset="utf-8"> -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   	<meta http-equiv="content-language" content="vi" />
   	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
   	<meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template" />
   	<meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal" />
	{% load static %}
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />
	<!-- Bootstrap CSS -->
	<!-- <link href="{% static 'dist/bootstrap5/css/bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" /> -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href= "{% static 'css/style_sidebar.css' %}" rel= "stylesheet" type= "text/css" />

	<style type="text/css">
		.breadcrumbs{position: fixed;width: 100%;z-index: 1000;}
		.breadcrumb{padding: .5rem 1rem;margin-bottom: 0;}
		.control-label{text-align: right;}
		.required-color{color: #ff6a00;}
		.footer{text-align: center;}
	</style>
</head>

  <body>
    <div id="wrapper">
		{% include 'layout/nav-bar_top.html' %}

		<div id="sidebar-wrapper">
			<nav class="sidebar">
				<div class="sidebar-header">
				<ul class="sidebar__toggled">
					<li><a href="javascript:void(0)" id="main-toggle" class="sidebar-toggle">{{ user.first_name }}
						{% if user.account.images %}
						<img src="{{ user.account.images.url }}" alt="" style="height:56px;width:56px;border-radius:50%;overflow:hidden;" />
						<!-- <img src="{{ MEDIA_URL }}{{ profile_record.images }}" alt="{{ profile_record.images }}" /> -->
						{% else %}
						<img src="{% static 'images/avatar.png' %}" alt="Default" style="height:56px;width:56px;border-radius:50%;overflow:hidden;"/>
						{% endif %}
					</a></li>
				</ul>
				</div>
			</nav>
			<nav id="sidebar" class="sidebar">
	            <ul class="list-unstyled components">
	                <p>Dummy Heading</p>
	                <!-- <li class="title">Item Group</li> -->
	                <li>
	                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><svg class="svg-inline--fa fa-home fa-w-18" aria-hidden="true" data-prefix="fas" data-icon="home" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="currentColor" d="M488 312.7V456c0 13.3-10.7 24-24 24H348c-6.6 0-12-5.4-12-12V356c0-6.6-5.4-12-12-12h-72c-6.6 0-12 5.4-12 12v112c0 6.6-5.4 12-12 12H112c-13.3 0-24-10.7-24-24V312.7c0-3.6 1.6-7 4.4-9.3l188-154.8c4.4-3.6 10.8-3.6 15.3 0l188 154.8c2.7 2.3 4.3 5.7 4.3 9.3zm83.6-60.9L488 182.9V44.4c0-6.6-5.4-12-12-12h-56c-6.6 0-12 5.4-12 12V117l-89.5-73.7c-17.7-14.6-43.3-14.6-61 0L4.4 251.8c-5.1 4.2-5.8 11.8-1.6 16.9l25.5 31c4.2 5.1 11.8 5.8 16.9 1.6l235.2-193.7c4.4-3.6 10.8-3.6 15.3 0l235.2 193.7c5.1 4.2 12.7 3.5 16.9-1.6l25.5-31c4.2-5.2 3.4-12.7-1.7-16.9z"></path></svg>
	                    Home</a>
	                    <ul class="collapse list-unstyled" id="homeSubmenu">
	                        <li><a href="{% url 'user:home' %}"><svg class="svg-inline--fa fa-home fa-w-18" aria-hidden="true" data-prefix="fas" data-icon="home" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="currentColor" d="M488 312.7V456c0 13.3-10.7 24-24 24H348c-6.6 0-12-5.4-12-12V356c0-6.6-5.4-12-12-12h-72c-6.6 0-12 5.4-12 12v112c0 6.6-5.4 12-12 12H112c-13.3 0-24-10.7-24-24V312.7c0-3.6 1.6-7 4.4-9.3l188-154.8c4.4-3.6 10.8-3.6 15.3 0l188 154.8c2.7 2.3 4.3 5.7 4.3 9.3zm83.6-60.9L488 182.9V44.4c0-6.6-5.4-12-12-12h-56c-6.6 0-12 5.4-12 12V117l-89.5-73.7c-17.7-14.6-43.3-14.6-61 0L4.4 251.8c-5.1 4.2-5.8 11.8-1.6 16.9l25.5 31c4.2 5.1 11.8 5.8 16.9 1.6l235.2-193.7c4.4-3.6 10.8-3.6 15.3 0l235.2 193.7c5.1 4.2 12.7 3.5 16.9-1.6l25.5-31c4.2-5.2 3.4-12.7-1.7-16.9z"></path></svg>
	                        Home</a></li>

						</ul>
	                </li>
	                <li>
	                    <a href="#"><svg class="svg-inline--fa fa-briefcase fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="briefcase" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M320 288h192v144c0 26.51-21.49 48-48 48H48c-26.51 0-48-21.49-48-48V288h192v20c0 6.627 5.373 12 12 12h104c6.627 0 12-5.373 12-12v-20zm192-112v80H0v-80c0-26.51 21.49-48 48-48h80V80c0-26.51 21.49-48 48-48h160c26.51 0 48 21.49 48 48v48h80c26.51 0 48 21.49 48 48zM320 96H192v32h128V96z"></path></svg>
	                    About</a>
	                </li>
	                <li>
	                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><svg class="svg-inline--fa fa-copy fa-w-14" aria-hidden="true" data-prefix="fas" data-icon="copy" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M320 448v40c0 13.255-10.745 24-24 24H24c-13.255 0-24-10.745-24-24V120c0-13.255 10.745-24 24-24h72v296c0 30.879 25.121 56 56 56h168zm0-344V0H152c-13.255 0-24 10.745-24 24v368c0 13.255 10.745 24 24 24h272c13.255 0 24-10.745 24-24V128H344c-13.2 0-24-10.8-24-24zm120.971-31.029L375.029 7.029A24 24 0 0 0 358.059 0H352v96h96v-6.059a24 24 0 0 0-7.029-16.97z"></path></svg>
	                    Pages</a>
	                    <ul class="collapse list-unstyled" id="pageSubmenu">
	                        <li>
	                            <a href="#">Page 1</a>
	                        </li>
	                        <li>
	                            <a href="#">Page 2</a>
	                        </li>
	                        <li>
	                            <a href="#">Page 3</a>
	                        </li>
	                    </ul>
	                </li>
	                <li>
	                    <a href="{% url 'user:profile' %}"><svg class="svg-inline--fa fa-briefcase fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="briefcase" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M320 288h192v144c0 26.51-21.49 48-48 48H48c-26.51 0-48-21.49-48-48V288h192v20c0 6.627 5.373 12 12 12h104c6.627 0 12-5.373 12-12v-20zm192-112v80H0v-80c0-26.51 21.49-48 48-48h80V80c0-26.51 21.49-48 48-48h160c26.51 0 48 21.49 48 48v48h80c26.51 0 48 21.49 48 48zM320 96H192v32h128V96z"></path></svg>
							Profile</a>
	                </li>
	                <li>
	                    <a href="#"><svg class="svg-inline--fa fa-paper-plane fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="paper-plane" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M476 3.2L12.5 270.6c-18.1 10.4-15.8 35.6 2.2 43.2L121 358.4l287.3-253.2c5.5-4.9 13.3 2.6 8.6 8.3L176 407v80.5c0 23.6 28.5 32.9 42.5 15.8L282 426l124.6 52.2c14.2 6 30.4-2.9 33-18.2l72-432C515 7.8 493.3-6.8 476 3.2z"></path></svg>
	                    Contact</a>
	                </li>
	            </ul>

	            <ul class="list-unstyled CTAs">
	                <li>
	                    <a href="#" class="download">Download source</a><!-- https://bootstrapious.com/tutorial/files/sidebar.zip -->
	                </li>
	                <li>
	                    <a href="#" class="article">Back to article</a><!-- https://bootstrapious.com/p/bootstrap-sidebar -->
	                </li>
	            </ul>
	        </nav>
		</div>


		<div id="page-content-wrapper">
		</div>
		<div class="container" style="margin-top: 38px;">{% block content %}{% endblock %}</div>
    </div>

	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

	<script type="text/javascript">
        $(document).ready(function () {
        	$(".sidebar-toggle").click(function(e) {
        		e.preventDefault();
        		$("#wrapper").toggleClass("toggled");
        	});

        	$("[data-role=dropdown]").dropdown();

        	/* Old */
        	$('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });

        	$("input[required], select[required]").attr("oninvalid", "this.setCustomValidity('Đây là thông tin bắt buộc')");
    		$("input[required], select[required]").attr("oninput", "setCustomValidity('')");
        });
    </script>
  </body>
</html>

user_app/templates/layout/nav-bar.html
<div class="nav">
  <a href="#">Go Home</a><!-- namespace:name -->
  <a href="#">About This Site</a>
  <a href="#">View Data</a>
</div>

user_app/templates/layout/nav-bar_top.html
{% load static %}
<div class="bs-example">
    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
        <!-- <a href="/" class="navbar-brand">Blog</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button> -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
            	<li class="nav-item"><a href="/" class="nav-link">Blog</a></li>
                <li class="nav-item"><a href="#" class="nav-link">About Us</a></li>
				<li class="nav-item"><a href="#" class="nav-link">Privacy Policy</a></li>
				<li class="nav-item"><a href="#" class="nav-link">Contact Us</a></li>
            </ul>
            <ul class="nav navbar-nav ml-auto pull-right">
            	<li><span class="navbar-brand">Call Us : 0989 968 279</span></li>
            	{% if not user.is_authenticated %}
            	<li class="nav-item">
                    <a href="{% url 'user:login' %}" class="nav-link">Login</a>
                </li>
                {% endif %}
            	<li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><img src="{% static 'images/vi.png' %}" alt="" />Tiếng Việt</a>
                    <div class="dropdown-menu">
                        <a href="#" data-lang="en" class="dropdown-item"><img src="{% static 'images/english.png' %}" alt="" />English</a>
						<a href="#" data-lang="vi" class="dropdown-item"><img src="{% static 'images/vi.png' %}" alt="" />Tiếng Việt</a>
                    </div>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" style="display: inline-block;">{{ user.first_name }}</a>
                    {% if user.profile.images %}
					<img src="{{ user.profile.images.url }}" alt="" style="height:35px;width:35px;border-radius:50%;overflow:hidden;" />
					<!-- <img src="{{ MEDIA_URL }}{{ profile_record.images }}" alt="{{ profile_record.images }}" /> -->
					{% else %}
					<img src="{% static 'images/avatar.png' %}" alt="Default" style="height:35px;width:35px;border-radius:50%;overflow:hidden;"/>
					{% endif %}
                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="{% url 'user:profile' %}" class="dropdown-item">Profile</a>
                        <!-- <a href="#" class="dropdown-item">Settings</a> -->
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'user:logout' %}"class="dropdown-item">Thoát</a>
                    </div>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

user_app/templates/layout/nav-sidebar.html

{% load static %}
{% if user.is_authenticated %}
	<!-- nav-sidebar: starts-here -->
	<div class="sidebar">
		<ul class="">
			<li><a href="https://docs.djangoproject.com/en/4.1/"><span
					class="icon_cog"></span>Documentation</a></li>
		</ul>
		<ul class="">
			<li><a href="../table/tablepage"><span class="icon_cog"></span>Table</a></li>
		</ul>
		<ul class="">
			<li><a href="https://www.djangoproject.com/download/"><span
					class="icon_star_alt"></span>Download</a></li>
		</ul>
		<ul class="">
			<li><a href="https://www.djangoproject.com/community/"><span
					class="icon_cog"></span>Community</a></li>
		</ul>
		<ul class="">
			<li><a href="../affiliate"><span
					class="icon_cog"></span>Affiliate</a></li>
		</ul>
	</div>
	<!-- sidebar-ends-here -->
{% endif %}